stages:
     - lint
     - build
     - scan

lint:
     stage: lint
     image: hadolint/hadolint:latest-debian
     before_script:
          - echo hadolint --version
     script:
          - echo "Execution du stage lint"
          - hadolint Dockerfile
     allow_failure: true
     
image: docker:latest

services:
     - docker:dind

before_script:
     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
     stage: build
     script:
          - docker build --pull -t "$CI_REGISTRY_IMAGE" .
          - docker push "$CI_REGISTRY_IMAGE"
     only:
          - master

build:
     stage: build
     script:
          - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
          - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
     except:
          - master

scan:
     stage: scan
     image: docker:stable
     services:
          - name: docker:dind
            entrypoint: ["env", "-u", "DOCKER_HOST"]
            command: ["dockerd-entrypoint.sh"]
     variables:
          DOCKER_HOST: tcp://docker:2375/
          DOCKER_DRIVER: overlay2
          DOCKER_TLS_CERTDIR: ""
          IMAGE: trivy-ci-test:$CI_COMMIT_SHA
     before_script:
          - apk add --no-cache curl
          - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          - echo $VERSION
          - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
          - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
     allow_failure: true
     script:
          # Construction du rapport
          - ./trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@contrib/gitlab.tpl" -o gl-container-scanning-report.json "$CI_REGISTRY_IMAGE"
          # Affichage du rapport
          - ./trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --severity HIGH $CI_REGISTRY_IMAGE
          # Échec des vulnérabilités élevées et critiques
          - ./trivy --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL --no-progress $CI_REGISTRY_IMAGE
     cache:
          paths:
               - .trivycache/
     artifacts:
          reports:
               container_scanning: gl-container-scanning-report.json
